---
- name: Add apt key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
    state: present
  tags: install

- name: Add mongod repository
  apt_repository:
    update_cache: yes
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: Install mongod
  apt:
    name: mongodb-org
    state: present
  tags: install

- name: Enable mongod
  systemd:
    name: mongod
    enabled: yes
  tags: install
